apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocky
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://johanneskastl.github.io/helm-charts
    chart: blocky
    targetRevision: 11.15.0
    helm:
      values: |
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi

        env:
          TZ: Europe/Zurich

        service:
          main:
            enabled: true
            ports:
              http:
                port: 4000
          dns:
            enabled: true
            type: LoadBalancer
            loadBalancerIP: "192.168.1.202"
            externalTrafficPolicy: Local
            ports:
              dns-tcp:
                enabled: true
                port: 53
                protocol: TCP
                targetPort: 53
              dns-udp:
                enabled: true
                port: 53
                protocol: UDP
                targetPort: 53

        metrics:
          enabled: false

        redis:
          enabled: false

        config: |
          upstreams:
            groups:
              default:
                - https://dns.quad9.net/dns-query
                - https://dns.mullvad.net/dns-query
            strategy: parallel_best
            timeout: 2s
          bootstrapDns:
            - 9.9.9.9
            - 149.112.112.112
          blocking:
            denylists:
              ads:
                - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/pro.txt
              adult:
                - https://nsfw.oisd.nl/domainswild2
                - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts
            clientGroupsBlock:
              default:
                - ads
                - adult
            blockType: zeroIp
            blockTTL: 1m
            loading:
              refreshPeriod: 24h
              downloads:
                timeout: 60s
                attempts: 5
              concurrency: 4
              strategy: failOnError
          caching:
            prefetching: true
            prefetchExpires: 24h
            prefetchThreshold: 2
          prometheus:
            enable: true
            path: /metrics
          ports:
            dns: 53
            http: 4000
  destination:
    server: https://kubernetes.default.svc
    namespace: blocky
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
