apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocky
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://dan1el-k.github.io/blocky-helm
    chart: blocky-helm
    targetRevision: 1.0.10
    helm:
      values: |
        env:
          - name: TZ
            value: "Europe/Zurich"

        service:
          type: LoadBalancer
          loadBalancerIP: "192.168.1.202"
          externalTrafficPolicy: Local

        config:
          ports:
            dns: 53
          upstreams:
            groups:
              default:
                - https://dns.quad9.net/dns-query
                - https://dns.mullvad.net/dns-query
            strategy: parallel_best
            timeout: 2s
          bootstrapDns:
            - 9.9.9.9
            - 149.112.112.112
          blocking:
            denylists:
              ads:
                - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/pro.txt
              adult:
                - https://nsfw.oisd.nl/domainswild2
                - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts
            clientGroupsBlock:
              default:
                - ads
                - adult
            blockType: zeroIp
            blockTTL: 1m
            loading:
              refreshPeriod: 24h
              downloads:
                timeout: 60s
                attempts: 5
              concurrency: 4
              strategy: failOnError
          caching:
            prefetching: true
            prefetchExpires: 24h
            prefetchThreshold: 2
          prometheus:
            enable: true
            path: /metrics

        ui:
          enabled: true
          service:
            enabled: true
            type: ClusterIP
            port: 8002

        redis:
          enabled: false

        k8sGateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: blocky
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
