apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/barnes-c/gitops-repo
      targetRevision: main
      path: manifests/immich
    - repoURL: https://immich-app.github.io/immich-charts
      chart: immich
      targetRevision: 0.10.3
      helm:
        values: |
          immich:
            persistence:
              library:
                existingClaim: immich-library

          controllers:
            main:
              containers:
                main:
                  env:
                    DB_HOSTNAME: immich-postgres
                    DB_PORT: "5432"
                    DB_DATABASE_NAME: immich
                    IMMICH_CONFIG_FILE: /config/immich.json
                  envFrom:
                    - secretRef:
                        name: immich-postgres-credentials

          persistence:
            immich-config:
              type: secret
              name: immich-config
              advancedMounts:
                main:
                  main:
                    - path: /config/immich.json
                      subPath: immich.json
                      readOnly: true

          machine-learning:
            controllers:
              main:
                pod:
                  nodeSelector:
                    workload/ml: "true"

          valkey:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
