apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/barnes-c/gitops-repo
        revision: main
        files:
          - path: manifests/monitoring/*/config.json
  template:
    metadata:
      name: "monitoring-{{ .name }}"
      namespace: argocd
    spec:
      project: default
      sources:
        - repoURL: "{{ .repoURL }}"
          chart: "{{ .chart }}"
          targetRevision: "{{ .chartVersion }}"
          helm:
            valueFiles:
              - $values/manifests/monitoring/{{ .name }}/values.yaml
        - repoURL: https://github.com/barnes-c/gitops-repo
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/warn: privileged
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/barnes-c/gitops-repo
    targetRevision: main
    path: manifests/monitoring
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-grafana-dashboards
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/barnes-c/gitops-repo
    targetRevision: main
    path: manifests/monitoring/grafana/dashboards
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
